### ISSUE TITLE
能补充一个requirements.txt文件嘛

### ISSUE THREAD

**Issue by Ymriri** [xrn1997/iToLoc#2]
如题，能补充一个requirements.txt文件嘛？因为不清楚作者您环境中各个依赖的版本，感谢！

**Comment by xrn1997** [comment]
可以，等我整理一下，因为之前只是用于保存代码，没想到还有人需要。

**Comment by Ymriri** [comment]
> 可以，等我整理一下，因为之前只是用于保存代码，没想到还有人需要。

直接使用pipreqs可以导出requirement.txt。最近刚好看到iToLoc学习学习，想问下您基本都实现了嘛？需要我后续自己补充内容嘛
